[build-system]
requires = ["hatchling", "numpy"]
build-backend = "hatchling.build"

[project]
name = "KTensors"
version = "0.0.6"
authors = [
  { name="Hanchao Zhang", email="hz1641@nyu.edu" },
]
description = "Clustering Positive Semi-Definite Tensors"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Hanchao-Zhang/KTensors"
"Bug Tracker" = "https://github.com/Hanchao-Zhang/KTensorsissues"